export const VIDEO_PLAY = 'VIDEO_PLAY';
export const VIDEO_MOVE_TIME = 'VIDEO_MOVE_TIME';
export const VIDEO_MUTE = 'VIDEO_MUTE';
export const VIDEO_CHANGE_VOLUME = 'VIDEO_CHANGE_VOLUME';
export const VIDEO_RUN_TIME = 'VIDEO_RUN_TIME';
export const VIDEO_EXPAND = 'VIDEO_EXPAND';
